import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "@/app/_style/globals.css";
import Header from "./_components/Header";

const nunito = Nunito({ subsets: ["vietnamese"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
